### ISSUE TITLE
How to check the centroids and the data in the clusters?

### ISSUE THREAD

**Issue by ravirajag** [AnswerDotAI/RAGatouille#207]
I have indexed around 11k sentences and it created some 4000 centroids. I am able to load the centroids file using the code
```python
from colbert.indexing.codecs.residual import ResidualCodec
res_codec = ResidualCodec.load(index_path)
```
I want to see what these 4000 centroids are (sentences). How should I get that?
I want to see what data goes under each cluster here.

**Comment by bclavie** [comment]
Hey, this is out of scope for RAGatouille, as it's very much a ColBERT-related research undertaking. I'd advise looking at the [main ColBERT repo](https://github.com/stanford-futuredata/ColBERT). If you're interested, there is also some research papers trying to better understand how PLAID indexing works!
