### ISSUE TITLE
Embedding Model with Existing Index

### ISSUE THREAD

**Issue by eyloncaplan** [AnswerDotAI/RAGatouille#218]
Hello! I'm wondering if there's any way to index a set of documents with one model, say model X, then to search the index using a different model, say model Y. In my case model Y would be a fine-tuned version of X, but in general I'd like to know. Otherwise I think I would have to reindex the whole set of documents using Y, which seems unnecessary in my case. Thank you!

**Comment by bclavie** [comment]
There isn't and it's not something that we're planning to support as the representations should be aligned between your indexing model and your querying model for better results!

If you're in one of the rare situations where this would produce good results, you can go and modify the `metadata.json` file that is present within your indexing folder. When loading a searcher, it'll by default seek to load the model in the `checkpoint` key of that json file, and modifying it to your model path (or HF identifier) will result in loading the new model!
