### ISSUE TITLE
Use base model or sentence transformer 

### ISSUE THREAD

**Issue by achibb** [AnswerDotAI/RAGatouille#225]
Hi there I wanted to Train a Colbert however I was wondering whether I should use a sentence transformers model or only a pre trained one. 

Also, is it possible to train with matryoshka embeddings?

**Comment by bclavie** [comment]
Hey!

Currently, you should only be using models that have been trained to work as multi-vector representers (and have the associated linear downcasting layer). This limitation might go away in the future as we support more flexible backends!
