### ISSUE TITLE
Question -- Symmetric search

### ISSUE THREAD

**Issue by dmacko232** [AnswerDotAI/RAGatouille#230]
Hello I am not able to find this information anywhere. But is it possible to use ColBERT model also for symmetric search? Lets say we have passages of ~300tokens and I would wanna find most similar ones (something like recommender/symmetric search).

**Comment by bclavie** [comment]
Hey, for this you'd want to just up the query maximum length to something pretty long, but it is doable and works pretty well -- in fact, it's done for one of the benchmarks in the original ColBERTv2 paper!
