### ISSUE TITLE
Typescript support of RAGatouille

### ISSUE THREAD

**Issue by purvapruthi** [AnswerDotAI/RAGatouille#234]
Hello, 

I want to use the RAGatouille library in a lightweight application and want to know if there is a typescript-compatible API that can be used to access the RAGatouille-created indices and initialize the RAGPretrained model. I'm trying to avoid using Python backend for latency purposes.

**Comment by bclavie** [comment]
Hey! This isn't currently planned/in-scope. It wouldn't, in theory, be too complicated, but for PLAID indexes, this'd require reproducing the ColBERT querying code in typescript.
