### ISSUE TITLE
Size Mismatch while training answerai-colbert-smallv1

### ISSUE THREAD

**Issue by Harrolee** [AnswerDotAI/RAGatouille#257]
Hi!

Awesome library. You're a champ, Ben.

The following error appeared while training colbert-small:
```
RuntimeError: Error(s) in loading state_dict for HF_ColBERT:
        size mismatch for linear.weight: copying a param with shape torch.Size([96, 384]) from checkpoint, the shape in current model is torch.Size([128, 384]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```

Does Ragatouille support training answerai-colbert-smallv1?
I'm on a macbook with an M1. Is this an mps vs cuda issue?

**Comment by Harrolee** [comment]
I found this note in the Ragatouille basic training notebook:
`Please note: Training can currently only be ran on GPU, and will error out if using CPU/MPS! Training is also currently not functional on Google`
Closing this issue. 👋

**Comment by bjsi** [comment]
When you call `train()` pass `dim=96` as a param
