### ISSUE TITLE
Was it supposed to be that SLOW?

### ISSUE THREAD

**Issue by dipta007** [AnswerDotAI/RAGatouille#259]
```python
# seqs1: 5 queries
# seqs2: 30 documents

RAG = RAGPretrainedModel.from_pretrained('hltcoe/plaidx-large-eng-tdist-mt5xxl-engeng', verbose=0)
RAG.encode([x for x in seqs2], verbose=False)
results = RAG.search_encoded_docs(query=seqs1, k=len(seqs2), bsize=256)
```

This code is taking 8 seconds to run. Am I doing something wrong?

**Comment by GoDjMike** [comment]
> # seqs1: 5 queries
> # seqs2: 30 documents
...
> RAG = RAGPretrainedModel.from_pretrained('hltcoe/plaidx-large-eng-tdist-mt5xxl-engeng', verbose=0)
> 
> RAG.encode([x for x in seqs2], verbose=False)
> 
> results = RAG.search_encoded_docs(query=seqs1, k=len(seqs2), bsize=256)

- Have you @dipta007 considered just loading your pretrained model just once and reloading it? That would decrease the overhead. (It's also a large model for a small dataset)
- if 'seqs2' isn't changing frequently, you could cache your doc embeddings?
- For this specific example, that batch size (256) is overkill

**Comment by dipta007** [comment]
1st one was the issue :( 
I was loading every time I was calling.
Thanks for the other suggestions, too.
